invoice/urls.py
from django.urls import path
from . import views

app_name = 'invoice'

urlpatterns = [
    path('add-invoice', views.AddInvoice.as_view(), name='add-invoice'),
    path('edit-invoice/<int:invoice_id>', views.EditInvoice.as_view(), name='edit-invoice'),
    path('remove-invoice/<int:invoice_id>', views.RemoveInvoice.as_view(), name='remove-invoice'),
    path('invoice-list', views.InvoiceList.as_view(), name='invoice-list'),
    path('invoice-details/<int:invoice_id>', views.ViewInvoice.as_view(), name='invoice-details'),


    # Ajax(s)
    path('fetch-info', views.FetchMedicineInfo.as_view(), name='fetch-med-info'),
    path('fetch-batch', views.FetchBatch.as_view(), name='fetch-batch'),
    path('fetch-customer', views.FetchCustomer.as_view(), name='fetch-customer'),
    path('fetch-batch-list', views.FetchBatchList.as_view(), name='fetch-batch-list'),
    path('remove-invoice-item', views.RemoveInvoiceItem.as_view(), name='remove-invoice-item'),
]

pms/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('users_auth.urls')),
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('manufacturer/', include('manufacturer.urls')),
    path('medicine/', include('medicine.urls')),
    path('bank/', include('bank.urls')),
    path('service/', include('service.urls')),
    path('purchase/', include('purchase.urls')),
    path('invoice/', include('invoice.urls')),
    path('settings/', include('settings.urls')),
    path('reports/', include('reports.urls')),
    path('employee/', include('employee.urls')),
    path('return/', include('return.urls')),
    path('accounts/', include('accounts.urls')),
    path('expense/', include('expense.urls')),
    path('attendance/', include('attendance.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoice/models.py
from django.db import models
from medicine.models import Medicine, Batch
from purchase.models import PAYMENT_TYPES, BANK_CHOICES


class Invoice(models.Model):
    customer = models.ForeignKey('customer.Customer', on_delete=models.SET_NULL, null=True, blank=True)
    date = models.DateField()
    invoice_number = models.CharField(max_length=200, null=True, blank=True)
    invoice_id = models.CharField(max_length=20, null=True, blank=True)
    details = models.CharField(max_length=200, null=True, blank=True)
    payment_types = models.IntegerField(choices=PAYMENT_TYPES, default=1)
    bank = models.IntegerField(choices=BANK_CHOICES, null=True, blank=True)

    invoice_discount = models.FloatField(default=0, null=True, blank=True)
    total_vat = models.FloatField(default=0, null=True, blank=True)
    paid_amount = models.FloatField(default=0, null=True, blank=True)

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.invoice_number

    @property
    def total_discount(self):
        total_discount = float(self.invoice_discount)
        discounts = []
        line_totals = []

        for item in self.invoiceitems_set.filter(is_active=True):
            if item.discount:
                discounts.append(item.discount)
            else:
                discounts.append(0)

            line_totals.append(item.total_bill)

        for index, value in enumerate(line_totals):
            line_discount = (value * discounts[index]) / 100
            total_discount += line_discount

        return total_discount

    @property
    def grand_total(self):
        line_totals = 0.0
        for item in self.invoiceitems_set.filter(is_active=True):
            line_totals += item.total_bill_exclude_vat

        return line_totals - self.invoice_discount

    @property
    def line_totals(self):
        line_totals = 0.0
        for item in self.invoice_items:
            line_totals += item.total_bill_exclude_vat
        return line_totals

    @property
    def net_total(self):
        return self.grand_total + self.customer.previous_balance

    @property
    def due_amount(self):
        due = 0.0
        if float(self.paid_amount) < float(self.net_total):
            due = float(self.net_total) - float(self.paid_amount)
        return due

    @property
    def change(self):
        change = 0.0
        if float(self.due_amount) == 0:
            change = float(self.paid_amount) - float(self.net_total)
        return change

    @property
    def invoice_items(self):
        return self.invoiceitems_set.filter(is_active=True)


class InvoiceItems(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.SET_NULL, null=True, blank=True)
    batch = models.ForeignKey(Batch, on_delete=models.SET_NULL, null=True, blank=True)
    sell_quantity = models.FloatField(default=0.0)
    price = models.FloatField(default=0.0)
    discount = models.FloatField(default=0.0)

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.sell_quantity)

    @property
    def total_bill(self):
        return float(self.sell_quantity) * float(self.price)

    @property
    def total_bill_exclude_vat(self):  # vat is not vat. It should be Discount. :|
        return float(self.total_bill) - (float(self.total_bill) * float(self.discount)) / 100

    @property
    def vat_amount(self):  # vat is not vat. It should be Discount. :|
        return float(self.total_bill) - float(self.total_bill_exclude_vat)

    @property
    def sell_return_combined(self):
        returned = 0
        for item in self.returned_item.filter(order__is_active=True):
            returned += item.return_quantity

        return self.sell_quantity - returned

invoice/views.py
import datetime

from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic.base import View

from customer.models import Customer
from invoice.models import Invoice, InvoiceItems
from medicine.models import Medicine, Batch
from purchase.models import PAYMENT_TYPES, BANK_CHOICES
from settings.models import Setting
from system.utils import random_id_generator


class AddInvoice(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, **kwargs):
        medicines = Medicine.objects.filter(is_active=True)
        current_invoice = 1000 + Invoice.objects.all().count() + 1
        customers = Customer.objects.filter(is_active=True)

        context = {
            'payment_types': list(PAYMENT_TYPES),
            'bank_choices': list(BANK_CHOICES),
            'medicines': medicines,
            'current_invoice': current_invoice,
            'customers': customers,
        }
        return render(request, 'invoice/add_invoice.html', context)

    def post(self, request):
        data = request.POST

        customer_id = data.get('customer')
        customer_obj = Customer.objects.get(id=customer_id)

        date = data.get('date')
        date = datetime.datetime.strptime(date, '%b %d, %Y').strftime('%Y-%m-%d')  # 2020-12-17

        invoice_no = data.get('invoice_no')
        details = data.get('details')
        payment_type = data.get('payment_type')
        bank_id = data.get('bank_id')

        medicine_ids_list = data.getlist('medicine_id[]')
        batch_ids_list = data.getlist('batch_id[]')
        sell_quantity_list = data.getlist('product_quantity[]')
        product_rate_list = data.getlist('product_rate[]')
        discount_list = data.getlist('discount[]')

        invoice_discount = data.get('invoice_discount') if data.get('invoice_discount') else 0
        total_vat = data.get('total_tax_amount') if data.get('total_tax_amount') else 0
        paid_amount = data.get('paid_amount') if data.get('paid_amount') else 0

        invoice_id = random_id_generator(module='Invoice')

        invoice_obj = Invoice(customer=customer_obj, date=date, invoice_number=invoice_no,
                              invoice_id=invoice_id, details=details, payment_types=payment_type,
                              bank=bank_id if bank_id != 'default' else None, invoice_discount=invoice_discount,
                              total_vat=total_vat, paid_amount=paid_amount)
        invoice_obj.save()


        # Saving InvoiceItems
        for i in range(len(medicine_ids_list)):

            batch_id = batch_ids_list[i]
            batch_obj = Batch.objects.get(id=batch_id)

            item_obj = InvoiceItems(batch=batch_obj, sell_quantity=sell_quantity_list[i] if sell_quantity_list[i] else 0,
                                    price=product_rate_list[i] if product_rate_list[i] else 0,
                                    discount=discount_list[i] if discount_list[i] else 0)

            item_obj.invoice = invoice_obj
            item_obj.save()

        # Calculating Customer's Current Balance

        if customer_obj.name == "Walking Customer":
            # No calculation needed for Walking Customers.
            pass
        else:
            customer_obj.previous_balance = customer_obj.current_balance
            if float(invoice_obj.due_amount) > 0:
                customer_obj.current_balance = float(invoice_obj.due_amount)
            else:
                if invoice_obj.change > 0:
                    customer_obj.current_balance = invoice_obj.change * -1
                else:
                    customer_obj.current_balance = invoice_obj.change

            # Changing Customer Status
            status = 2 if float(customer_obj.current_balance) > 0 else 1
            customer_obj.status = status
            customer_obj.save()

        messages.success(request, 'Invoice Added Successfully. ')
        return redirect('invoice:add-invoice')


class InvoiceList(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        invoices = Invoice.objects.filter(is_active=True)

        all_invoice_total = 0
        for invoice in invoices:
            all_invoice_total += invoice.net_total

        context = {
            'invoices': invoices,
            'invoices_total': all_invoice_total,
        }

        return render(request, 'invoice/invoice_list.html', context)


class EditInvoice(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, invoice_id):
        invoice_obj = Invoice.objects.get(id=invoice_id)
        medicines = Medicine.objects.filter(is_active=True)
        customers = Customer.objects.filter(is_active=True)
        invoice_items = invoice_obj.invoiceitems_set.filter(is_active=True)

        context = {
            'object': invoice_obj,
            'payment_types': list(PAYMENT_TYPES),
            'bank_choices': list(BANK_CHOICES),
            'medicines': medicines,
            'customers': customers,
            'invoice_items': invoice_items,

        }

        return render(request, 'invoice/update_invoice.html', context)

    def post(self, request, invoice_id):
        invoice_obj = Invoice.objects.get(id=invoice_id)

        data = request.POST
        customer_id = data.get('customer')
        customer_obj = Customer.objects.get(id=customer_id)

        date = data.get('date')
        try:
            date = datetime.datetime.strptime(date, '%b %d, %Y').strftime('%Y-%m-%d')  # 2020-12-17
        except:
            date = invoice_obj.date

        invoice_no = data.get('invoice_no')
        details = data.get('details')
        payment_type = data.get('payment_type')
        bank_id = data.get('bank_id')

        medicine_ids_list = data.getlist('medicine_id[]')
        batch_ids_list = data.getlist('batch_id[]')
        sell_quantity_list = data.getlist('product_quantity[]')
        product_rate_list = data.getlist('product_rate[]')
        discount_list = data.getlist('discount[]')
        item_ids_list = data.getlist('items[]')

        invoice_discount = data.get('invoice_discount') if data.get('invoice_discount') else 0
        total_vat = data.get('total_tax_amount') if data.get('total_tax_amount') else 0

        paid_amount = data.get('paid_amount') if data.get('paid_amount') else 0

        invoice_obj.customer = customer_obj
        invoice_obj.date = date
        invoice_obj.invoice_number = invoice_no
        invoice_obj.details = details
        invoice_obj.payment_types = payment_type
        invoice_obj.bank = bank_id if bank_id != 'default' else None
        invoice_obj.invoice_discount = float(invoice_discount)
        invoice_obj.total_vat = total_vat
        invoice_obj.paid_amount = paid_amount
        invoice_obj.save()

        updated_items = len(item_ids_list)

        # Updating Existing Items
        for index, item_id in enumerate(item_ids_list):

            batch_obj = Batch.objects.get(id=int(batch_ids_list[index]))

            item_obj = InvoiceItems.objects.get(id=int(item_id))
            item_obj.sell_quantity = sell_quantity_list[index]
            item_obj.discount = discount_list[index]
            item_obj.batch = batch_obj
            item_obj.price = product_rate_list[index]
            item_obj.save()

        if len(medicine_ids_list) > updated_items:
            # Adding New InvoiceItems
            for i in range(updated_items, len(medicine_ids_list)):
                batch_id = batch_ids_list[i]
                batch_obj = Batch.objects.get(id=batch_id)

                item_obj = InvoiceItems(batch=batch_obj,
                                        sell_quantity=sell_quantity_list[i] if sell_quantity_list[i] else 0,
                                        price=product_rate_list[i] if product_rate_list[i] else 0,
                                        discount=discount_list[i] if discount_list[i] else 0)

                item_obj.invoice = invoice_obj
                item_obj.save()

                # Rechecking Quantity
                if batch_obj.sold_quantity > batch_obj.batch_stock:
                    item_obj.delete()
                    messages.info(request, "PURCHASE ERROR! Recheck Quantity.")
                    return redirect('invoice:edit-invoice', invoice_id=invoice_id)

        # Calculating Customer's Current Balance
        if customer_obj.name == "Walking Customer":
            # No calculation needed for Walking Customers.
            pass
        else:
            if float(invoice_obj.due_amount) > 0:
                customer_obj.current_balance = float(invoice_obj.due_amount)
            else:
                if invoice_obj.change > 0:
                    customer_obj.current_balance = invoice_obj.change * -1
                else:
                    customer_obj.current_balance = invoice_obj.change

            # Changing Customer Status
            status = 2 if float(customer_obj.current_balance) > 0 else 1
            customer_obj.status = status
            customer_obj.save()

        messages.success(request, 'Invoice Updated Successfully. ')
        return redirect('invoice:edit-invoice', invoice_id=invoice_id)


class RemoveInvoice(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, invoice_id):
        invoice_obj = Invoice.objects.get(id=invoice_id)
        invoice_obj.is_active = False
        invoice_obj.save()

        # for item in invoice_obj.invoiceitems_set.filter(is_active=True):
        #     item.batch.batch_stock -= item.sell_quantity
        #     item.batch.save()

        messages.success(request, 'Invoice Removed Successfully. ')

templates/invoice/invoice_list.html
    {% extends  'base.html' %}
{% load static %}
{% block title %}
    <title>Invoice List</title>
{% endblock title %}


{% block styles %}
{% endblock styles %}

{% block content %}

    {% include 'sidebar.html' %}

    <div class="content-wrapper" style="min-height: 201px;">
        <!-- Content Header (Page header) -->
        {% include 'navbar.html' %}
        <!-- /.content-header -->

        <span> {% include 'messages.html' %} </span>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->

                <div class="body-content px-3 py-3">


                    <div class="row">
                        <div class="col-md-12 col-md-12">
                            <div class="card ">
                                <div class="card-header py-2">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div>
                                            <h6 class="fs-17 font-weight-600 mb-0">Invoice List</h6>
                                        </div>
                                        <div class="text-right">
                                            <a href="{% url 'invoice:add-invoice' %}"
                                               class="btn btn-success btn-sm mr-1"><i class="fas fa-plus mr-1"></i>Add
                                                Invoice</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <form action="" class="form-inline" method="post">
                                                <label class="sr-only" for="from_date">Start Date</label>
                                                <div class="input-group mb-2 mr-sm-2">
                                                    <div class="input-group-prepend">
                                                        <div class="input-group-text">Start Date</div>
                                                    </div>
                                                    <input type="text" class="form-control datepicker psdate"
                                                           name="from_date" id="from_date" placeholder="Start Date"
                                                           value="">
                                                </div>
                                                <label class="sr-only" for="to_date">End Date</label>
                                                <div class="input-group mb-2 mr-sm-2">
                                                    <div class="input-group-prepend">
                                                        <div class="input-group-text">End Date</div>
                                                    </div>
                                                    <input type="text" class="form-control datepicker pedate"
                                                           id="to_date" name="to_date" placeholder="End Date">
                                                </div>
                                                <button type="button" id="btn-filter-pur" class="btn btn-success mb-2">
                                                    Find
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="table-responsive">
                                        <div id="InvoicList_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                            <table class="table table-striped table-bordered custom-table dataTable dtr-inline"
                                                   cellspacing="0" width="100%" id="InvoicList" role="grid"
                                                   aria-describedby="InvoicList_info" style="width: 100%;">
                                                <thead>
                                                <tr role="row">
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 41px;" aria-label="Sl">Sl
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 127px;" aria-label="Invoice No">Invoice No
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 154px;" aria-label="Invoice Id">Invoice Id
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 184px;" aria-label="Customer Name">Customer Name
                                                    </th>
                                                    <th class="sorting_desc" tabindex="0" aria-controls="InvoicList"
                                                        rowspan="1" colspan="1" style="width: 109px;"
                                                        aria-sort="descending"
                                                        aria-label="Date: activate to sort column ascending">Date
                                                    </th>
                                                    <th class="total_sale text-right sorting_disabled" rowspan="1"
                                                        colspan="1" style="width: 159px;" aria-label="Total Amount">
                                                        Total Amount
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 155px;" aria-label="Action">Action
                                                    </th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for invoice in invoices %}

                                                    <tr role="row">
                                                        <td tabindex="0">{{ forloop.counter }} </td>
                                                        <td>{{ invoice.invoice_number }}</td>
                                                        <td>{{ invoice.invoice_id }}</td>
                                                        <td>{{ invoice.customer.name }}</td>
                                                        <td class="sorting_1">{{ invoice.date }}</td>
                                                        <td class=" total_sale text-right">{{ invoice.net_total }}</td>
                                                        <td>
                                                            <a href="{% url 'invoice:invoice-details' invoice.invoice_id %}"
                                                               class="btn btn-success-soft btn-sm" data-toggle="tooltip"
                                                               data-placement="left" title="Details"><i class="fas fa-eye"
                                                                                                        aria-hidden="true"></i></a>
                                                            <a href=""
                                                               class="btn btn-warning-soft btn-sm" data-toggle="tooltip"
                                                               data-placement="left" title="POS Print"><i class="fas fa-fax"
                                                                                                          aria-hidden="true"></i></a>
                                                            <a href="{% url 'invoice:edit-invoice' invoice.id %}"
                                                               class="btn btn-primary-soft btn-sm" data-toggle="tooltip"
                                                               data-placement="left" title="Update"><i class="fas fa-edit"
                                                                                                       aria-hidden="true"></i></a>
                                                            <a onclick="return confirm('Are You Sure ?')"
                                                               href="{% url 'invoice:remove-invoice' invoice.id %}"
                                                               class="btn btn-danger-soft btn-sm" data-toggle="tooltip"
                                                               data-placement="right" title="Delete "><i
                                                                    class="far fa-trash-alt" aria-hidden="true"></i></a>
                                                        </td>
                                                    </tr>

                                                {% endfor %}

                                                </tbody>
                                                <tfoot>
                                                <tr>
                                                    <th colspan="5" class="text-right" rowspan="1">Total:</th>
                                                    <th class="total_sale text-right" rowspan="1" colspan="1"> &#2547;
                                                        {{ invoices_total }}
                                                    </th>
                                                    <th rowspan="1" colspan="1"></th>
                                                </tr>
                                                </tfoot>
                                            </table>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </section>
    </div>

{% endblock content %}

{% block scripts %}


{% endblock scripts %}