expense/urls.py
from django.urls import path
from . import views

app_name = 'expense'

urlpatterns = [

   # Expense Item
   path('expense-items/', views.ExpenseItemList.as_view(), name='expense_items'),
   path('add-expense-item/', views.AddExpenseItem.as_view(), name='add_expense_item'),
   path('update-expense-item/<int:item_id>', views.UpdateExpenseItem.as_view(), name='update_expense_item'),
   path('remove-expense-item/<int:item_id>', views.UpdateExpenseItem.as_view(), name='remove_expense_item'),

   # Expense
   path('expense-list/', views.ExpenseList.as_view(), name='expense_list'),
   path('add-expense/', views.AddExpense.as_view(), name='add_expense'),
   path('remove-expense/<int:expense_id>', views.UpdateExpense.as_view(), name='remove_expense'),  # get request

]

pms/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('users_auth.urls')),
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('manufacturer/', include('manufacturer.urls')),
    path('medicine/', include('medicine.urls')),
    path('bank/', include('bank.urls')),
    path('service/', include('service.urls')),
    path('purchase/', include('purchase.urls')),
    path('invoice/', include('invoice.urls')),
    path('settings/', include('settings.urls')),
    path('reports/', include('reports.urls')),
    path('employee/', include('employee.urls')),
    path('return/', include('return.urls')),
    path('accounts/', include('accounts.urls')),
    path('expense/', include('expense.urls')),
    path('attendance/', include('attendance.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expense/models.py
from django.db import models

from purchase.models import PAYMENT_TYPES, BANK_CHOICES


class ExpenseItem(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name[:20]


class Expense(models.Model):
    date = models.DateField()
    expense_type = models.ForeignKey(ExpenseItem, on_delete=models.SET_NULL, null=True, blank=True)
    payment_type = models.IntegerField(choices=PAYMENT_TYPES, null=True, blank=True)
    bank = models.IntegerField(choices=BANK_CHOICES, null=True, blank=True)
    amount = models.FloatField(default=0)
    remarks = models.TextField(null=True, blank=True)

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.expense_type} --> {self.amount}"

expense/views.py
import datetime

from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import View

from expense.models import ExpenseItem, Expense
from purchase.models import PAYMENT_TYPES, BANK_CHOICES


class ExpenseItemList(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        items = ExpenseItem.objects.filter(is_active=True)
        context = {
            'items': items
        }
        return render(request, 'expense/expense_items_list.html', context)



class AddExpenseItem(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request):
        name = request.POST.get('item_name')
        obj = ExpenseItem(name=name)
        obj.save()

        messages.success(request, "Expense Item Added Successfully. ")
        return redirect('expense:expense_items')


class UpdateExpenseItem(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, item_id):  # used to remove Expense Item
        item_obj = ExpenseItem.objects.get(id=item_id)
        item_obj.is_active = False
        item_obj.save()

        messages.success(request, 'Item Removed Successfully. ')
        return redirect('expense:expense_items')

    def post(self, request, item_id):
        data = request.POST
        name = data.get('item_name')

        item_obj = ExpenseItem.objects.get(id=item_id)
        item_obj.name = name
        item_obj.save()

        messages.success(request, 'Item Updated Successfully. ')
        return redirect('expense:expense_items')


class ExpenseList(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        expenses = Expense.objects.filter(is_active=True)
        context = {
            'expenses': expenses
        }
        return render(request, 'expense/expense_list.html', context)

    def post(self, request):
        pass


class AddExpense(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):

        expense_items = ExpenseItem.objects.filter(is_active=True)
        context = {
            'payment_types': list(PAYMENT_TYPES),
            'banks': list(BANK_CHOICES),
            'expense_items': expense_items,
        }

        return render(request, 'expense/add_expense.html', context)

    def post(self, request):
        data = request.POST
        date = data.get('dtpDate')
        date = datetime.datetime.strptime(date, '%b %d, %Y').strftime('%Y-%m-%d')  # 2020-12-17
        expense_type = data.get('expense_type')
        item_obj = ExpenseItem.objects.get(id=expense_type)

        payment_type = data.get('payment_type')
        bank = data.get('bank_id')
        amount = data.get('amount')
        note = data.get('note', '')

        expense_obj = Expense(date=date, expense_type=item_obj, payment_type=payment_type, amount=float(amount),
                              remarks=note)
        if bank:
            expense_obj.bank = bank
        expense_obj.save()

        messages.success(request, 'Expense Added Successfully. ')
        return redirect('expense:expense_list')


class UpdateExpense(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, expense_id):  # used to remove Expense Item
        expense_obj = Expense.objects.get(id=expense_id)
        expense_obj.is_active = False
        expense_obj.save()

        messages.success(request, 'Expense Removed Successfully. ')
        return redirect('expense:expense_list')

    def post(self, request, item_id):  # not required
        pass

templates/expense/add_expense.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Add Expense</title>
{% endblock title %}


{% block styles %}
{% endblock styles %}



{% block content %}

    {% include 'sidebar.html' %}

    <div class="content-wrapper" style="min-height: 201px;">
        <!-- Content Header (Page header) -->
        {% include 'navbar.html' %}
        <!-- /.content-header -->

        <span> {% include 'messages.html' %} </span>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->

                <div class="body-content px-3 py-3" data-select2-id="select2-data-15-t0xf">


                    <div class="row" data-select2-id="select2-data-14-491u">
                        <div class="col-sm-12 col-md-12" data-select2-id="select2-data-13-qazj">
                            <div class="card " data-select2-id="select2-data-12-pns3">
                                <div class="card-header py-2">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div>
                                            <h4 class="fs-17 font-weight-600 mb-0">Add Expense</h4>
                                        </div>
                                        <div class="text-right">
                                            <a href="{% url 'expense:expense_list' %}"
                                               class="btn btn-success btn-sm mr-1"><i class="fas fa-list mr-1"></i>
                                                Expense List</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body" data-select2-id="select2-data-11-3ko7">
                                    <form action="{% url 'expense:add_expense' %}"
                                          enctype="multipart/form-data" method="post" accept-charset="utf-8"> {% csrf_token %}
                                        <div class="row" data-select2-id="select2-data-9-zp6n">
                                            <div class="col-sm-12">
                                                <div class="form-group row">
                                                    <label for="date" class="col-sm-3 col-form-label">Date <i
                                                            class="text-danger">*</i>
                                                    </label>
                                                    <div class="col-sm-8">
                                                        <input type="text" name="dtpDate" id="dtpDate"
                                                               class="form-control datepicker" required>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-12" id="payment_from_1">
                                                <div class="form-group row">
                                                    <label for="expense_type" class="col-sm-3 col-form-label">Expense
                                                        Type <i class="text-danger">*</i></label>
                                                    <div class="col-sm-8">
                                                        <select name="expense_type"
                                                                class="form-control"
                                                                tabindex="-1"
                                                                aria-hidden="true">
                                                            <option value="default">
                                                                Select Expense Type
                                                            </option>
                                                            {% for item in expense_items %}
                                                                <option value="{{ item.id }}">{{ item.name }}</option>
                                                            {% endfor %}

                                                        </select>
                                                    </div>
                                                </div>
                                            </div>


                                            <div class="form-group row">
                                                <label for="payment_type" class="col-md-3 col-form-label">Payment
                                                    Type<i class="text-danger"> * </i>:</label>
                                                <div class="col-md-8">
                                                    <div class="">
                                                        <select name="payment_type" id="payment_type"
                                                                class="form-control"
                                                                tabindex="-1"
                                                                aria-hidden="true">
                                                            {% for payment_type in payment_types %}
                                                                <option value="{{ payment_type.0 }}">{{ payment_type.1 }}</option>
                                                            {% endfor %}
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>

                                        <div class="form-group row d-none" id="bank_div">
                                            <label for="bank" class="col-md-3 col-form-label"
                                                       id="bank_label"
                                                >Bank: <i class="text-danger">*</i></label>
                                                <div class="col-md-8">
                                                    <div class="">
                                                        <select name="bank_id"
                                                                class="form-control"
                                                                id="bank_id"
                                                                tabindex="-1" aria-hidden="true">
                                                            <option value="" selected="selected"
                                                                    data-select2-id="select2-data-6-xio6">Select Bank
                                                            </option>
                                                            {% for bank in banks %}

                                                                <option value="{{ bank.0 }}"> {{ bank.1 }} </option>

                                                            {% endfor %}

                                                        </select>
                                                    </div>
                                        </div>
                                            </div>

                                            <div class="col-sm-12" id="payment_from_1">
                                                <div class="form-group row">
                                                    <label for="date" class="col-sm-3 col-form-label">Amount<i
                                                            class="text-danger">*</i></label>
                                                    <div class="col-sm-8">
                                                        <input type="text" name="amount" id="amount" maxlength="10"
                                                               class="form-control numberField" required>
                                                    </div>
                                                </div>
                                            </div>


                                         <div class="col-sm-12" id="remarks">
                                                <div class="form-group row">
                                                    <label for="date" class="col-sm-3 col-form-label">Note: <i
                                                            ></i></label>
                                                    <div class="col-sm-8">
                                                        <textarea name="note" rows="4"
                                                                  class="form-control"> </textarea>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-sm-12 text-right">
                                                <div class="form-group row">
                                                    <label class="col-sm-3"></label>
                                                    <div class="col-sm-8">
                                                        <input type="submit" id="add_receive"
                                                               class="btn btn-success btn-large" name="save"
                                                               value="Save" tabindex="9">
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                <!-- /.row (main row) -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

{% endblock content %}


{% block scripts %}

    <script>
    $(document).ready(function () {
        $("#payment_type").on('change', function () {
            let payment_type = $("#payment_type").val();
            if (payment_type == 1) {
                $("#bank_div").addClass('d-none');
            } else {
                $("#bank_div").removeClass('d-none');
            }
        });
    });
    </script>
{% endblock scripts %}

templates/expense/expense_items_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Expense Item</title>
{% endblock title %}


{% block styles %}
{% endblock styles %}



{% block content %}

    {% include 'sidebar.html' %}

    <div class="content-wrapper" style="min-height: 201px;">
        <!-- Content Header (Page header) -->
        {% include 'navbar.html' %}
        <!-- /.content-header -->

        <span> {% include 'messages.html' %} </span>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->

                <div class="body-content px-3 py-3">


                    <div class="row">
                        <div class="col-md-12 col-md-12">
                            <div class="card ">
                                <div class="card-header py-2">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div>
                                            <h6 class="fs-17 font-weight-600 mb-0">Expense Items</h6>
                                        </div>
                                        <div class="text-right">
                                            <button data-toggle="modal" data-target="#add_item"
                                               class="btn btn-success btn-sm mr-1"><i class="fas fa-plus mr-1"></i>Add
                                                </button>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <div id="CustomerList_wrapper" class="dataTables_wrapper dt-bootstrap4">

                                            <table class="table display table-bordered table-striped table-hover"
                                                   cellspacing="0" width="100%" id="ManufacturerList" role="grid"
                                                   aria-describedby="CustomerList_info" style="width: 100%;">
                                                <thead>
                                                <tr role="row">
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 15px;" aria-label="Sl">Sl
                                                    </th>
                                                    <th width="220px;" class="sorting_asc"
                                                        aria-controls="CustomerList"
                                                        style="" aria-sort="ascending"
                                                        aria-label="Customer Name: activate to sort column descending">
                                                        Item Type
                                                    </th>

                                                    <th width="30px;" class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 43px;" aria-label="Action">Action
                                                    </th>
                                                </tr>
                                                </thead>
                                                <tbody>

                                                {% for item in items %}

                                                    <tr role="row">
                                                        <td tabindex="0">{{ forloop.counter }}</td>
                                                        <td class="font-weight-normal">{{ item.name }}</td>
                                                        <td>
                                                            <button data-toggle="modal" data-target="#update_item{{ item.id }}"
                                                               class="btn btn-success btn-sm" data-toggle="tooltip"
                                                               data-placement="left" title="Update"><i class="fas fa-edit"
                                                                                                       aria-hidden="true"></i></button>

                                                            {% include 'expense/modals/upadate_item.html' %}

                                                            <a onclick="return confirm('Are You Sure ?')"
                                                               href="{% url 'expense:remove_expense_item' item.id %}"
                                                               class="btn btn-danger btn-sm" data-toggle="tooltip"
                                                               data-placement="right" title="Delete "><i
                                                                    class="far fa-trash-alt" aria-hidden="true"></i></a>
                                                        </td>
                                                    </tr>
                                                {% endfor %}

                                                </tbody>
                                            </table>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>


                <!-- /.row (main row) -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

    {% include 'expense/modals/add_item.html' %}

{% endblock content %}


{% block script %}
{% endblock script %}

templates/expense/expense_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Expense List</title>
{% endblock title %}


{% block styles %}
{% endblock styles %}



{% block content %}

    {% include 'sidebar.html' %}

    <div class="content-wrapper" style="min-height: 201px;">
        <!-- Content Header (Page header) -->
        {% include 'navbar.html' %}
        <!-- /.content-header -->

        <span> {% include 'messages.html' %} </span>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->


                <div class="col-md-12 col-md-12">
                    <div class="card ">
                        <div class="card-header py-2">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                    <h4 class="fs-17 font-weight-600 mb-0">Expense List</h4>
                                </div>
                                <div class="text-right">
                                    <a href="{% url 'expense:add_expense' %}"
                                       class="btn btn-success btn-sm mr-1"><i class="fas fa-plus mr-1"></i>Add
                                        Expense</a>

                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <form action="" class="form-inline" method="post" accept-charset="utf-8">
                                        <label class="sr-only" for="from_date">Start Date</label>
                                        <div class="input-group mb-2 mr-sm-2">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">Start Date</div>
                                            </div>
                                            <input type="text" class="form-control datepicker psdate" name="from_date"
                                                   id="from_date" placeholder="Start Date" value="">
                                        </div>
                                        <label class="sr-only" for="to_date">End Date</label>
                                        <div class="input-group mb-2 mr-sm-2">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">End Date</div>
                                            </div>
                                            <input type="text" class="form-control datepicker pedate" id="to_date"
                                                   name="to_date" placeholder="End Date">
                                        </div>
                                        <button type="button" id="btn-filter-pur" class="btn btn-success mb-2">Find
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <div id="expenseList_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">

                                    <table class="table display table-bordered table-striped table-hover no-footer dtr-inline"
                                           cellspacing="0" width="100%" id="expenseList" role="grid"
                                           aria-describedby="expenseList_info" style="width: 100%;">
                                        <thead>
                                        <tr role="row">
                                            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 55px;"
                                                aria-label="Sl">Sl
                                            </th>
                                            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 149px;"
                                                aria-label="Date">Date
                                            </th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="expenseList" rowspan="1"
                                                colspan="1" style="width: 202px;" aria-sort="ascending"
                                                aria-label="Expense Item: activate to sort column descending">Expense
                                                Item
                                            </th>
                                            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 98px;"
                                                aria-label="Debit">Amount
                                            </th>

                                            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 208px;"
                                                aria-label="Remarks">Note
                                            </th>
                                            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 111px;"
                                                aria-label="Action">Action
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for expense in expenses %}

                                            <tr role="row" class="odd">
                                            <td tabindex="0">{{ forloop.counter }}</td>
                                            <td>{{ expense.date | date:"M d, Y" }}</td>
                                            <td class="sorting_1">{{ expense.expense_type.name }}</td>
                                            <td>{{ expense.amount }}</td>
                                            <td>{{ expense.remarks }}</td>
                                            <td><a onclick="return confirm('Are You Sure ?')"
                                                   href="{% url 'expense:remove_expense' expense.id %}"
                                                   class="btn btn-danger btn-sm" data-toggle="tooltip"
                                                   data-placement="right" title="Delete "><i class="far fa-trash-alt"
                                                                                             aria-hidden="true"></i></a>
                                            </td>
                                        </tr>

                                        {% endfor %}

                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- /.row (main row) -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

{% endblock content %}


{% block scripts %}

    <script>
        $(document).ready(function () {
            $("#expenseList").DataTable();
        });
    </script>
{% endblock scripts %}