customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('add-customer/', views.AddCustomer.as_view(), name='add-customer'),
    path('customer-list/', views.CustomerList.as_view(), name='customer-list'),
    path('edit-customer/<str:customer_id>', views.EditCustomer.as_view(), name='edit-customer'),
    path('remove-customer/<int:customer_id>', views.RemoveCustomer.as_view(), name='remove-customer'),
    path('paid-customer/', views.PaidCustomer.as_view(), name='paid-customer'),
    path('credit-customer/', views.CreditCustomer.as_view(), name='credit-customer'),
]

pms/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('users_auth.urls')),
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('manufacturer/', include('manufacturer.urls')),
    path('medicine/', include('medicine.urls')),
    path('bank/', include('bank.urls')),
    path('service/', include('service.urls')),
    path('purchase/', include('purchase.urls')),
    path('invoice/', include('invoice.urls')),
    path('settings/', include('settings.urls')),
    path('reports/', include('reports.urls')),
    path('employee/', include('employee.urls')),
    path('return/', include('return.urls')),
    path('accounts/', include('accounts.urls')),
    path('expense/', include('expense.urls')),
    path('attendance/', include('attendance.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models as dbModel
from system.utils import CUSTOMER_STATUS


class Customer(dbModel.Model):
    name = dbModel.CharField(max_length=200)
    mobile_number = dbModel.CharField(max_length=13)
    first_email = dbModel.EmailField(max_length=50, null=True, blank=True)
    second_email = dbModel.EmailField(max_length=50, null=True, blank=True)
    phone = dbModel.CharField(max_length=15, null=True, blank=True)
    contact = dbModel.CharField(max_length=200, null=True, blank=True)
    first_address = dbModel.CharField(max_length=200, null=True, blank=True)
    second_address = dbModel.CharField(max_length=200, null=True, blank=True)
    fax = dbModel.CharField(max_length=200, null=True, blank=True)
    city = dbModel.CharField(max_length=200, null=True, blank=True)
    state = dbModel.CharField(max_length=200, null=True, blank=True)
    zip = dbModel.CharField(max_length=200, null=True, blank=True)
    country = dbModel.CharField(max_length=200, null=True, blank=True)
    previous_balance = dbModel.FloatField(default=0.00, null=True, blank=True)
    current_balance = dbModel.FloatField(default=0.00, null=True, blank=True)
    status = dbModel.IntegerField(choices=CUSTOMER_STATUS)

    is_active = dbModel.BooleanField(default=True)

    def __str__(self):
        return self.name

customer/views.py
from django.contrib import messages
from django.db.models import Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import View

from customer.models import Customer


class AddCustomer(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        context = {

        }
        return render(request, 'customer/add_customer.html', context)

    def post(self, request):
        if request.method == "POST":
            data = request.POST
            customer_name = data.get('customer_name')
            customer_mobile = data.get('customer_mobile')
            first_email = data.get('first_email', '')
            second_email = data.get('second_email', '')
            phone = data.get('phone', '')
            contact = data.get('contact', '')
            first_address = data.get('first_address', '')
            second_address = data.get('second_address', '')
            fax = data.get('fax', '')
            city = data.get('city', '')
            state = data.get('state', '')
            zip_code = data.get('zip', '')
            country = data.get('country', '')
            current_balance = data.get('previous_balance')

            status = 2 if float(current_balance) > 0 else 1

            customer_object = Customer(name=customer_name, mobile_number=customer_mobile, first_email=first_email,
                                       second_email=second_email, phone=phone, contact=contact, first_address=first_address,
                                       second_address=second_address, fax=fax, city=city, state=state, zip=zip_code,
                                       country=country, current_balance=current_balance, status=status)

            messages.success(request, "Customer Added Successfully. ")
            customer_object.save()
            return redirect('customer:add-customer')


class CustomerList(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        customers = Customer.objects.filter(is_active=True)
        total_bills = customers.aggregate(Sum('current_balance'))['current_balance__sum']

        context = {
            'customers': customers,
            'total_bills': total_bills,
            'category': 'Customers List',
        }
        return render(request, 'customer/customer_list.html', context)

    def post(self, request):
        pass


class EditCustomer(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, customer_id):
        customer_obj = get_object_or_404(Customer, pk=int(customer_id))
        context = {
            'customer': customer_obj
        }
        return render(request, 'customer/edit_customer.html', context)

    def post(self, request, customer_id):
        customer_obj = get_object_or_404(Customer, pk=int(customer_id))
        if request.method == "POST":
            data = request.POST
            customer_name = data.get('customer_name')
            customer_mobile = data.get('customer_mobile')
            first_email = data.get('first_email', '')
            second_email = data.get('second_email', '')
            phone = data.get('phone', '')
            contact = data.get('contact', '')
            first_address = data.get('first_address', '')
            second_address = data.get('second_address', '')
            fax = data.get('fax', '')
            city = data.get('city', '')
            state = data.get('state', '')
            zip_code = data.get('zip', '')
            country = data.get('country', '')
            current_balance = data.get('previous_balance')

            status = 2 if float(current_balance) > 0 else 1

            customer_obj.name = customer_name
            customer_obj.mobile_number = customer_mobile
            customer_obj.first_email = first_email
            customer_obj.second_email = second_email
            customer_obj.phone = phone
            customer_obj.contact = contact
            customer_obj.first_address = first_address
            customer_obj.second_address = second_address
            customer_obj.fax = fax
            customer_obj.city = city
            customer_obj.state = state
            customer_obj.zip = zip_code
            customer_obj.country = country
            customer_obj.current_balance = current_balance
            customer_obj.status = status
            messages.success(request, "Customer Updated Successfully. ")
            customer_obj.save()

            return redirect('customer:edit-customer', customer_id=customer_id)


class RemoveCustomer(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, customer_id):
        customer_obj = get_object_or_404(Customer, pk=customer_id)
        customer_obj.is_active = False
        customer_obj.save()
        messages.success(request, 'Customer Deleted Successfully. ')
        return redirect('customer:customer-list')


class PaidCustomer(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        paid_customers = Customer.objects.filter(status=1, is_active=True)
        total_bills = paid_customers.aggregate(Sum('previous_balance'))['previous_balance__sum']
        context = {
            'customers': paid_customers,
            'category': 'Paid Customers',
            'total_bills': total_bills,
        }
        return render(request, 'customer/customer_list.html', context)


class CreditCustomer(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        credit_customers = Customer.objects.filter(status=2, is_active=True)
        total_bills = credit_customers.aggregate(Sum('previous_balance'))['previous_balance__sum']
        context = {
            'customers': credit_customers,
            'category': 'Credit Customers',
            'total_bills': total_bills,
        }
        return render(request, 'customer/customer_list.html', context)

templates/customer/customer_list.html
{% extends  'base.html' %}

{% block title %}
    <title>Customer List</title>
{% endblock title %}


{% block styles %}
{% endblock styles %}

{% block content %}

    {% include 'sidebar.html' %}

    <div class="content-wrapper" style="min-height: 201px;">
        <!-- Content Header (Page header) -->
        {% include 'navbar.html' %}
        <!-- /.content-header -->

        <span> {% include 'messages.html' %} </span>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->

                <div class="body-content px-3 py-3">


                    <div class="row">
                        <div class="col-md-12 col-md-12">
                            <div class="card ">
                                <div class="card-header py-2">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div>
                                            <h6 class="fs-17 font-weight-600 mb-0">{{ category }}</h6>
                                        </div>
                                        <div class="text-right">
                                            <a href="{% url 'customer:add-customer' %}"
                                               class="btn btn-success btn-sm mr-1"><i class="fas fa-plus mr-1"></i>Add
                                                Customer</a>

                                        {% ifequal category "Customers List" %}

                                            <a href="{% url 'customer:paid-customer' %}"
                                               class="btn btn-info btn-sm"><i class="fas fa-align-justify mr-1"></i>Credit
                                                Customer</a>

                                            <a href="{% url 'customer:credit-customer' %}"
                                               class="btn btn-primary btn-sm"><i class="fas fa-align-justify mr-1"></i>Paid
                                                Customer</a>

                                        {% endifequal %}


                                        {% ifequal category "Credit Customers" %}

                                             <a href="{% url 'customer:customer-list' %}"
                                           class="btn btn-info btn-sm"><i class="fas fa-align-justify mr-1"></i>
                                            Customers List</a>

                                            <a href="{% url 'customer:paid-customer' %}"
                                           class="btn btn-primary btn-sm"><i class="fas fa-align-justify mr-1"></i>Paid
                                            Customer</a>
                                        {% endifequal %}

                                        {% ifequal category "Paid Customers" %}

                                            <a href="{% url 'customer:customer-list' %}"
                                           class="btn btn-info btn-sm"><i class="fas fa-align-justify mr-1"></i>
                                            Customers List</a>

                                            <a href="{% url 'customer:credit-customer' %}"
                                           class="btn btn-primary btn-sm"><i class="fas fa-align-justify mr-1"></i>Credit
                                            Customer</a>

                                        {% endifequal %}

                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <div id="CustomerList_wrapper" class="dataTables_wrapper dt-bootstrap4">

                                            <table class="table display table-bordered table-striped table-hover"
                                                   cellspacing="0" width="100%" id="CustomerList" role="grid"
                                                   aria-describedby="CustomerList_info" style="width: 100%;">
                                                <thead>
                                                <tr role="row">
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 15px;" aria-label="Sl">Sl
                                                    </th>
                                                    <th width="220px;" class="sorting_asc"
                                                        aria-controls="CustomerList"
                                                        style="" aria-sort="ascending"
                                                        aria-label="Customer Name: activate to sort column descending">
                                                        Customer <br> Name
                                                    </th>
                                                    <th width="90px;" class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 90px;" aria-label="Address 1">Address 1
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 74px;" aria-label="Mobile No">Mobile No
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 122px;" aria-label="Email">Email
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 29px;" aria-label="City">City
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 39px;" aria-label="State">State
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 24px;" aria-label="Zip">Zip
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 64px;" aria-label="Country">Country
                                                    </th>
                                                    <th class="balance text-right sorting_disabled" rowspan="1"
                                                        colspan="1" style="width: 61px;" aria-label="Balance"> Due Balance
                                                    </th>
                                                    <th width="30px;" class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 43px;" aria-label="Action">Action
                                                    </th>
                                                </tr>
                                                </thead>
                                                <tbody>

                                                {% for customer in customers %}

                                                    <tr role="row">
                                                        <td tabindex="0">{{ forloop.counter }}</td>
                                                        <td class="">{{ customer.name }}</td>
                                                        <td>{{ customer.first_address }}</td>
                                                        <td>{{ customer.mobile_number }}</td>
                                                        <td>{{ customer.first_email }}</td>
                                                        <td>{{ customer.city }}</td>
                                                        <td>{{ customer.state }}</td>
                                                        <td>{{ customer.zip }}</td>
                                                        <td>{{ customer.country }}</td>
                                                        <td class=" balance text-right">{{ customer.current_balance | floatformat:2 }}</td>
                                                        <td style="width: 10%">
                                                            <div class="btn-group">
                                                                <a href="{% url 'customer:edit-customer' customer.id %}" style="margin-right: 5px;"><button class="btn btn-success fa fa-edit"></button></a>
                                                                <a href="{% url 'customer:remove-customer' customer.id %}" style="margin-right: 5px;"><button class="btn btn-danger far fa-trash-alt"></button></a>
                                                            </div>
                                                        </td>

                                                    </tr>
                                                {% endfor %}


                                                </tbody>
                                                <tfoot>
                                                <tr>
                                                    <th colspan="9" class="text-right" rowspan="1">Total:</th>
                                                    <th id="total_balance" class="text-right" rowspan="1"
                                                        colspan="1">BDT {{ total_bills | floatformat:2 }}
                                                    </th>
                                                    <th rowspan="1" colspan="1"></th>
                                                </tr>
                                                </tfoot>
                                            </table>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>


                <!-- /.row (main row) -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>


{% endblock content %}

{% block scripts %}

    <script>
    $(document).ready(function() {

    // Applying Datatable & calculating Total Balance Dynamically.
    $('#CustomerList').DataTable( {
        "footerCallback": function ( row, data, start, end, display ) {
            var api = this.api(), data;

            // Remove the formatting to get integer data for summation
            var intVal = function ( i ) {
                return typeof i === 'string' ?
                    i.replace(/[\$,]/g, '')*1 :
                    typeof i === 'number' ?
                        i : 0;
            };

            // Total over all pages
            total = api
                .column( 9 )
                .data()
                .reduce( function (a, b) {
                    return intVal(a) + intVal(b);
                }, 0 );

            // Total over this page
            pageTotal = api
                .column( 9, { page: 'current'} )
                .data()
                .reduce( function (a, b) {
                    return intVal(a) + intVal(b);
                }, 0 );

            // Update footer
            $("#total_balance").html(pageTotal.toFixed(2))
        }
    } );
} );
</script>
{% endblock scripts %}