pms/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('users_auth.urls')),
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('manufacturer/', include('manufacturer.urls')),
    path('medicine/', include('medicine.urls')),
    path('bank/', include('bank.urls')),
    path('service/', include('service.urls')),
    path('purchase/', include('purchase.urls')),
    path('invoice/', include('invoice.urls')),
    path('settings/', include('settings.urls')),
    path('reports/', include('reports.urls')),
    path('employee/', include('employee.urls')),
    path('return/', include('return.urls')),
    path('accounts/', include('accounts.urls')),
    path('expense/', include('expense.urls')),
    path('attendance/', include('attendance.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purchase/urls.py
from django.urls import path
from . import views

app_name = 'purchase'

urlpatterns = [
    path('add-purchase', views.AddPurchase.as_view(), name='add-purchase'),
    path('purchase-list', views.PurchaseList.as_view(), name='purchase-list'),
    path('view-purchase/<int:purchase_id>', views.ViewPurchase.as_view(), name='view-purchase'),
    path('update-purchase/<int:purchase_id>', views.UpdatePurchase.as_view(), name='update-purchase'),
    path('remove-purchase/<int:purchase_id>', views.RemovePurchase.as_view(), name='remove-purchase'),

    # Ajax Calls
    path('fetch-medicines/', views.FetchMedicines.as_view(), name='fetch-medicine'),
    path('fetch-price/', views.FetchPrice.as_view(), name='fetch_price'),
    path('fetch-quantity', views.FetchQuantity.as_view(), name='fetch-quantity'),
    path('remove-purchase-item', views.RemovePurchaseItem.as_view(), name='remove-purchase-item'),

]

purchase/models.py
from django.db import models
from medicine.models import Medicine, Leaf, Batch
from manufacturer.models import Manufacturer


PAYMENT_TYPES = (
    (1, 'Cash Payment'),
    (2, 'Bank Payment')
)

BANK_CHOICES = (
    (1, 'City Bank'),
    (2, 'UCB'),
    (3, 'DBBl'),
    (4, 'Prime Asia'),
)


class Purchase(models.Model):
    purchase_id = models.IntegerField(unique=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.SET_NULL, null=True, blank=True)
    date = models.DateField()
    invoice = models.CharField(max_length=100, null=True, blank=True)
    details = models.TextField()
    payment_types = models.IntegerField(choices=PAYMENT_TYPES, default=1)
    bank = models.IntegerField(choices=BANK_CHOICES, null=True, blank=True)

    vat = models.FloatField(default=0)
    discount = models.FloatField(default=0)
    paid_amount = models.FloatField(default=0)

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.invoice

    @property
    def subtotal(self):
        subtotal = 0
        for value in self.purchaseitems_set.filter(is_active=True):
            subtotal += value.calculated_price
        return subtotal

    @property
    def grand_total(self):
        return self.subtotal + self.vat - self.discount

    @property
    def due_amount(self):
        return self.grand_total - self.paid_amount

    @property
    def purchase_items(self):
        return self.purchaseitems_set.filter(is_active=True)


class PurchaseItems(models.Model):
    order = models.ForeignKey(Purchase, on_delete=models.SET_NULL, null=True, blank=True)
    batch = models.ForeignKey(Batch, on_delete=models.SET_NULL, null=True, blank=True)

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "{a}".format(a=self.order)

    @property
    def calculated_price(self):
        medicine_price = self.batch.medicine.manufacturer_price
        return self.batch.box_quantity * medicine_price

purchase/views.py
import datetime
import random

from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import View

from manufacturer.models import Manufacturer
from medicine.models import Leaf, Medicine, Batch
from settings.models import Setting
from system.utils import random_id_generator
from .models import BANK_CHOICES, PAYMENT_TYPES, Purchase, PurchaseItems


class AddPurchase(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        manufacturers = Manufacturer.objects.filter(is_active=True)
        leafs = Leaf.objects.all()

        context = {
            'manufacturers': manufacturers,
            'leafs': leafs,
            'banks': list(BANK_CHOICES),
            'payment_types': list(PAYMENT_TYPES),
        }

        return render(request, 'purchase/add_purchase.html', context)

    def post(self, request):
        data = request.POST

        purchase_id = random_id_generator('Purchase')

        manufacturer_id = data.get('manufacturer_id')
        manufacturer_obj = Manufacturer.objects.get(id=manufacturer_id)

        purchase_date = request.POST.get('date')  # Dec 18, 2020
        purchase_date = datetime.datetime.strptime(purchase_date, '%b %d, %Y').strftime('%Y-%m-%d')  # 2020-12-17

        invoice_no = data.get('invoice_no')
        details = data.get('details', '')
        payment_type = data.get('payment_type')
        bank_id = data.get('bank_id')

        medicine_list = data.getlist('medicine_name[]')
        batch_id_list = data.getlist('batch_id[]')
        expire_date_list = data.getlist('expire_date[]')
        leaf_type_list = data.getlist('leaf_type[]')
        box_quantity_list = data.getlist('box_quantity[]')
        product_quantity_list = data.getlist('product_quantity[]')

        vat = data.get('vat')
        discount = data.get('discount')
        paid_amount = float(data.get('paid_amount'))
        due_amount = float(data.get('due_amount'))

        purchase_obj = Purchase(purchase_id=purchase_id, manufacturer=manufacturer_obj, date=purchase_date, invoice=invoice_no,
                                details=details, payment_types=payment_type, bank=bank_id if bank_id else None,
                                vat=vat if vat else 0, discount=discount if discount else 0, paid_amount=paid_amount if paid_amount else 0)
        purchase_obj.save()

        # Saving Purchase Items
        for i in range(len(medicine_list)):  # loop will execute number of rows times

            expire_date = expire_date_list[i]  # Dec 18, 2020 format
            expire_date = datetime.datetime.strptime(expire_date, '%b %d, %Y').strftime('%Y-%m-%d')  # 2020-12-17

            item_obj = PurchaseItems()

            medicine_obj = Medicine.objects.get(pk=medicine_list[i])
            leaf_obj = Leaf.objects.get(id=leaf_type_list[i])

            batch, created = Batch.objects.get_or_create(medicine=medicine_obj, batch_number=batch_id_list[i])

            batch.expiry_date = expire_date
            batch.box_pattern = leaf_obj
            batch.box_quantity = box_quantity_list[i]
            batch.previous_stock = batch.batch_stock
            batch.batch_stock += int(product_quantity_list[i])
            batch.save()

            item_obj.order = purchase_obj
            item_obj.batch = batch
            item_obj.save()

        messages.success(request, 'Purchase Added Successfully. ')

        # updating Current Balance of Manufacturer
        # If balance is positive, Manufacturer will get money from shop
        # else shop will get money from manufacturer

        manufacturer_obj.previous_balance += due_amount
        manufacturer_obj.save()

        return redirect('purchase:purchase-list')


class PurchaseList(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        purchases = Purchase.objects.filter(is_active=True)

        total_purchases = 0
        for purchase in purchases:
            total_purchases += purchase.grand_total

        context = {
            'purchases': purchases,
            'total_purchases': total_purchases,
        }
        return render(request, 'purchase/purchase_list.html', context)


class UpdatePurchase(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, purchase_id):
        purchase_obj = Purchase.objects.get(id=purchase_id)
        manufacturers = Manufacturer.objects.filter(is_active=True)
        leafs = Leaf.objects.all()

        context = {
            'object': purchase_obj,
            'manufacturers': manufacturers,
            'payment_types': list(PAYMENT_TYPES),
            'banks': list(BANK_CHOICES),
            'items': purchase_obj.purchaseitems_set.filter(is_active=True),
            'leafs': leafs,
        }
        return render(request, 'purchase/update_purchase.html', context)

    def post(self, request, purchase_id):
        data = request.POST

        manufacturer_id = data.get('manufacturer_id')
        manufacturer_obj = Manufacturer.objects.get(id=manufacturer_id)

        purchase_date = request.POST.get('date')  # Dec 18, 2020

        try:
            purchase_date = datetime.datetime.strptime(purchase_date, '%b %d, %Y').strftime('%Y-%m-%d')  # 2020-12-17
        except:
            purchase_date = purchase_date

        details = data.get('details', '')
        invoice_no = data.get('invoice_no')
        payment_type = data.get('payment_type')
        bank_id = data.get('bank_id')

        medicine_list = data.getlist('medicine_name[]')
        batch_id_list = data.getlist('batch_id[]')
        expire_date_list = data.getlist('expire_date[]')
        leaf_type_list = data.getlist('leaf_type[]')
        box_quantity_list = data.getlist('box_quantity[]')
        product_quantity_list = data.getlist('product_quantity[]')
        items_id_list = data.getlist('items[]')

        vat = data.get('vat')
        discount = data.get('discount')
        paid_amount = data.get('paid_amount')

        purchase_obj = Purchase.objects.get(id=purchase_id)
        purchase_obj.manufacturer = manufacturer_obj
        purchase_obj.date = purchase_date
        purchase_obj.invoice = invoice_no
        purchase_obj.details = details
        purchase_obj.payment_types = payment_type
        purchase_obj.bank = bank_id if bank_id else None
        purchase_obj.vat = vat if vat else 0
        purchase_obj.discount = discount if discount else 0
        purchase_obj.paid_amount = paid_amount if paid_amount else 0
        purchase_obj.save()

        # Updating Existing Objects
        for index, item_id in enumerate(items_id_list):
            expire_date = expire_date_list[index]
            try:
                expire_date = datetime.datetime.strptime(expire_date, '%b %d, %Y').strftime('%Y-%m-%d')  # 2020-12-17
            except:
                expire_date = expire_date

            item_obj = PurchaseItems.objects.get(id=int(item_id))
            batch_obj = item_obj.batch

            medicine_obj = Medicine.objects.get(pk=medicine_list[index])
            leaf_obj = Leaf.objects.get(id=leaf_type_list[index])

            batch_obj.medicine = medicine_obj
            batch_obj.box_pattern = leaf_obj
            batch_obj.box_quantity = float(box_quantity_list[index])
            batch_obj.batch_number = batch_id_list[index]
            batch_obj.batch_stock = int(float(product_quantity_list[index]))
            batch_obj.expiry_date = expire_date
            batch_obj.save()
            item_obj.save()

        updated_batches = len(items_id_list)

        if len(medicine_list) > updated_batches:

            # Saving New Purchase Items
            for i in range(updated_batches, len(medicine_list)):  # loop will execute number of rows times
                expire_date = expire_date_list[updated_batches]  # Dec 18, 2020

                try:
                    expire_date = datetime.datetime.strptime(expire_date, '%b %d, %Y').strftime('%Y-%m-%d')  # 2020-12-17
                except:
                    expire_date = expire_date

                batch = Batch()
                item_obj = PurchaseItems()

                medicine_obj = Medicine.objects.get(pk=medicine_list[updated_batches])
                leaf_obj = Leaf.objects.get(id=leaf_type_list[updated_batches])

                batch.box_pattern = leaf_obj
                batch.box_quantity = float(box_quantity_list[updated_batches])
                batch.batch_stock = int(float(product_quantity_list[updated_batches]))
                batch.medicine = medicine_obj
                batch.batch_number = batch_id_list[updated_batches]
                batch.expiry_date = expire_date
                batch.save()

                item_obj.order = purchase_obj
                item_obj.batch = batch
                item_obj.save()

        messages.success(request, 'Purchase Updated Successfully. ')
        return redirect('purchase:purchase-list')


class RemovePurchase(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, purchase_id):
        purchase_obj = Purchase.objects.get(id=purchase_id)
        purchase_obj.is_active = False

        for item in purchase_obj.purchase_items:
            item.batch.batch_stock -= item.batch.total_quantity
            item.batch.save()

        purchase_obj.save()

        messages.success(request, 'Purchase Removed Successfully. ')
        return redirect('purchase:purchase-list')


class ViewPurchase(View):
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, purchase_id):

templates/purchase/purchase_list.html
{% extends  'base.html' %}
{% load static %}
{% block title %}
    <title>Purchase List</title>
{% endblock title %}


{% block styles %}
{% endblock styles %}

{% block content %}

    {% include 'sidebar.html' %}

    <div class="content-wrapper" style="min-height: 201px;">
        <!-- Content Header (Page header) -->
        {% include 'navbar.html' %}
        <!-- /.content-header -->

        <span> {% include 'messages.html' %} </span>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->

                <div class="body-content px-3 py-3">


                    <div class="row">
                        <div class="col-md-12 col-md-12">
                            <div class="card ">
                                <div class="card-header py-2">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div>
                                            <h6 class="fs-17 font-weight-600 mb-0">Purchase List</h6>
                                        </div>
                                        <div class="text-right">
                                            <a href="{% url 'purchase:add-purchase' %}"
                                               class="btn btn-success btn-sm mr-1"><i class="fas fa-plus mr-1"></i>Add
                                                Purchase</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <form action="" class="form-inline" method="post" accept-charset="utf-8">
                                                <label class="sr-only" for="from_date">Start Date</label>
                                                <div class="input-group mb-2 mr-sm-2">
                                                    <div class="input-group-prepend">
                                                        <div class="input-group-text">Start Date</div>
                                                    </div>
                                                    <input type="text" class="form-control datepicker"
                                                           name="from_date" id="from_date" placeholder="Start Date"
                                                           >
                                                </div>
                                                <label class="sr-only" for="to_date">End Date</label>
                                                <div class="input-group mb-2 mr-sm-2">
                                                    <div class="input-group-prepend">
                                                        <div class="input-group-text">End Date</div>
                                                    </div>
                                                    <input type="text" class="form-control datepicker"
                                                           id="to_date" name="to_date" placeholder="End Date">
                                                </div>
                                                <button type="button" id="btn-filter-pur" class="btn btn-success mb-2">
                                                    Find
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="table-responsive">
                                        <div id="PurList_wrapper" class="dataTables_wrapper dt-bootstrap4">

                                            <table class="table table-striped table-bordered custom-table dataTable dtr-inline"
                                                   cellspacing="0" width="100%" id="PurList" role="grid"
                                                   aria-describedby="PurList_info" style="width: 100%;">
                                                <thead>
                                                <tr role="row">
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 41px;" aria-label="Sl">Sl
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 128px;" aria-label="Invoice No">Invoice No
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 154px;" aria-label="Purchase Id">Purchase Id
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 222px;" aria-label="Manufacturer Name">
                                                        Manufacturer Name
                                                    </th>
                                                    <th class="sorting_desc" tabindex="0" aria-controls="PurList"
                                                        rowspan="1" colspan="1" style="width: 110px;"
                                                        aria-sort="descending"
                                                        aria-label="Date: activate to sort column ascending">Date
                                                    </th>
                                                    <th class="total_sale text-right sorting_disabled" rowspan="1"
                                                        colspan="1" style="width: 160px;" aria-label="Total Amount">
                                                        Total Amount
                                                    </th>
                                                    <th class="sorting_disabled" rowspan="1" colspan="1"
                                                        style="width: 114px;" aria-label="Action">Action
                                                    </th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for purchase in purchases %}

                                                    <tr role="row">
                                                        <td tabindex="0">{{ forloop.counter }}</td>
                                                        <td>{{ purchase.invoice }}</td>
                                                        <td>{{ purchase.purchase_id }}</td>
                                                        <td>{{ purchase.manufacturer.name }}</td>
                                                        <td>{{ purchase.date| date:"M d, Y" }}</td>
                                                        <td class="total_sale text-right">{{ purchase.grand_total }}</td>
                                                        <td>
                                                            <a href="{% url 'purchase:view-purchase' purchase.id %}"
                                                               class="btn btn-success-soft btn-sm" data-toggle="tooltip"
                                                               data-placement="left" title="Details"><i class="fas fa-eye"
                                                                                                        aria-hidden="true"></i></a>
                                                            <a href="{% url 'purchase:update-purchase' purchase.id %}"
                                                               class="btn btn-primary-soft btn-sm" data-toggle="tooltip"
                                                               data-placement="left" title="Update"><i class="fas fa-edit"
                                                                                                       aria-hidden="true"></i></a>
                                                            <a onclick="return confirm('Are You Sure ?')"
                                                               href="{% url 'purchase:remove-purchase' purchase.id %}"
                                                               class="btn btn-danger-soft btn-sm" data-toggle="tooltip"
                                                               data-placement="right" title="Delete "><i
                                                                    class="far fa-trash-alt" aria-hidden="true"></i></a>
                                                        </td>
                                                    </tr>

                                                {% endfor %}

                                                </tbody>
                                                <tfoot>
                                                    <tr>
                                                        <th colspan="5" class="text-right" rowspan="1">Total:</th>
                                                        <th class="total_sale text-right" rowspan="1" colspan="1">
                                                            {{ total_purchases }}
                                                        </th>
                                                        <th rowspan="1" colspan="1"></th>
                                                    </tr>
                                                </tfoot>
                                            </table>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>


            </div>
        </section>
    </div>

{% endblock content %}

{% block scripts %}

{% endblock scripts %}